### ISSUE TITLE
Implement accessors without instantiating

### ISSUE THREAD

**Issue by asgrim** [Roave/BetterReflection#14]
Comment from @Ocramius (see [here](https://github.com/Roave/BetterReflection/pull/11/files#r33757929))

> You can create an accessor even without the instance of the object or internal reflection.
> 
> See http://ocramius.github.io/blog/accessing-private-php-class-members-without-reflection/

This would mean we could support the following methods:
- [x] `ReflectionClass::getStaticPropertyValue` - see #114 
- [x] `ReflectionClass::setStaticPropertyValue` - see #114 
- [x] `ReflectionMethod::getClosure` - see #354
- [x] `ReflectionMethod::invoke` - see #355
- [x] `ReflectionMethod::invokeArgs` - see #355
- [x] `ReflectionMethod::setAccessible` - see #355
- [x] `ReflectionFunction::getClosure` - see #357
- [x] `ReflectionFunction::invoke` - see #357
- [x] `ReflectionFunction::invokeArgs` - see #357
- [x] `ReflectionProperty::setAccessible` - see #343
- [x] `ReflectionProperty::setValue` - see #343

**Comment by asgrim** [comment]
Related to #7

**Comment by asgrim** [comment]
Some currently-failing .phpt tests for `invoke`, `setAccessible`, and `setValue` can be found: https://gist.github.com/asgrim/4cd0d4ca9f7165754419458ffbfec467

**Comment by kukulich** [comment]
Some accessors implemented in https://github.com/Roave/BetterReflection/pull/343

**Comment by kukulich** [comment]
@Ocramius Could you please check methods in the description that are done now?

**Comment by Ocramius** [comment]
@kukulich done

**Comment by kukulich** [comment]
`ReflectionMethod::getClosure()` implemented in https://github.com/Roave/BetterReflection/pull/354

**Comment by kukulich** [comment]
`ReflectionMethod::invoke()`, `ReflectionMethod::invokeArgs()` and `ReflectionMethod::setAccessible()` implemented in https://github.com/Roave/BetterReflection/pull/355

**Comment by kukulich** [comment]
`ReflectionFunction::invoke()`, `ReflectionFunction::invokeArgs()` and `ReflectionFunction::getClosure()` implemented in https://github.com/Roave/BetterReflection/pull/357

**Comment by Ocramius** [comment]
Shipped! Thanks for the hard work, @kukulich!
